export default {
  packagesUploading: [],
  packages: {},
  delegations: [
    {
      label: 'My Uploads',
      value: 'custom',
      key: 'custom',
      uri: 'api/v1/user_repo/targets.json',
      source: 'user',
      buildType: 'custom',
    },
    {
      label: 'Torizon LTS',
      value: 'tdx/lts',
      key: 'tdx-lts',
      uri: '/api/metadata/delegations/tdx/lts',
      source: 'toradex',
      buildType: 'lts',
    },
    {
      label: 'Torizon Release',
      value: 'tdx/quarterly',
      key: 'tdx-quarterly',
      uri: '/api/metadata/delegations/tdx/quarterly',
      source: 'toradex',
      buildType: 'release',
    },
    {
      label: 'Torizon Monthly',
      value: 'tdx/monthly',
      key: 'tdx-monthly',
      uri: '/api/metadata/delegations/tdx/monthly',
      source: 'toradex',
      buildType: 'monthly',
    },
    {
      label: 'Torizon Nightly',
      value: 'tdx/nightly',
      key: 'tdx-nightly',
      uri: '/api/metadata/delegations/tdx/nightly',
      source: 'toradex',
      buildType: 'nightly',
    },
    {
      label: 'Torizon Demo Apps',
      value: 'tdx/containers',
      key: 'tdx-containers',
      uri: '/api/metadata/delegations/tdx/containers',
      source: 'toradex',
      buildType: 'custom',
    },
  ],
  defaultSelectedDelegationSources: ['tdx-lts', 'tdx-quarterly', 'tdx-monthly', 'custom'],
  selectedDelegationSources: [],
  trustedDelegations: [],
  deltas: {},
};
