CREATE TABLE DeviceTag (
  namespace  VARCHAR(255) NOT NULL,
  tag_id     SMALLINT     NOT NULL,
  tag_name   VARCHAR(200) NOT NULL,
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (namespace, tag_id),
  UNIQUE (namespace, tag_name)
);
