# version: '3.8'

# TODO: Some proxy for reposerver.ota.ce and such so don't have to use proxies

# TODO: Kafka

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.3
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --providers.docker.exposedbydefault=false
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  gateway:
    image: nginx:1.13.7
    restart: always
    command: ["nginx-debug", "-g", "daemon off;"]      
    expose:
      - '80'
      - '443'
      - '8443'
    ports:
#      - '80'
      - '8443'
      - '30443:8443'
    depends_on:
      - ota-lith
      - reverse-proxy
    volumes:
      - ./ota-ce/gateway.conf:/etc/nginx/conf.d/gateway.conf:ro
      - ./ota-ce-gen/server.chain.pem:/etc/ssl/gateway/server.chain.pem:ro
      - ./ota-ce-gen/server.key:/etc/ssl/gateway/server.key:ro
      - ./ota-ce-gen/devices/ca.crt:/etc/ssl/gateway/ca.crt:ro

  webapp:
    image: advancedtelematic/ota-plus-web:48fed9434c838536a1d90e32d4ffe59bae708cd2
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.service=app
      - traefik.http.routers.app.rule=Host(`app.ota.ce`)
      - traefik.http.services.app.loadbalancer.server.port=9000
    environment:
      JAVA_OPTS: "-Dtrace.zipkin.sample-rate=0"
      CAMPAIGNER_HOST: "ota-lith"
      CAMPAIGNER_PORT: "7600"
      DEVICE_REGISTRY_HOST: "ota-lith"
      DEVICE_REGISTRY_PORT: "7500"
      TUF_REPOSERVER_HOST: "ota-lith"
      TUF_REPOSERVER_PORT: "7100"
      TUF_KEYSERVER_HOST: "ota-lith"
      TUF_KEYSERVER_HOST: "7200"
      DIRECTOR_HOST: "ota-lith"
      DIRECTOR_PORT: "7300"
      PLAY_CRYPTO_SECRET: youshouldreplacethiswithsomeotherlongsecret
      JWT_SECRET: eW91c2hvdWxkcmVwbGFjZXRoaXN3aXRoc29tZW90aGVybG9uZ3NlY3JldA==
      PLAY_HTTP_SESSION_SECURE: "false"
      OIDC_KEYSET: '{"keys": []}'
      OIDC_NS_PROVIDER: "com.advancedtelematic.auth.oidc.ConfiguredNamespace"
      OIDC_LOGIN_ACTION: "com.advancedtelematic.auth.NoLoginAction"
      OIDC_LOGOUT_ACTION: "com.advancedtelematic.auth.NoLogoutAction"
      MESSAGING_MODE: "test" #TODO
      ATS_HTTP_TRACING: "false"
      ATS_LOG_LEVEL: "debug"
      WS_HOST: "app.ota.ce"
      WS_PORT: '80'
      WS_SCHEME: ws            
      NAMESPACE_DIRECTOR_MODULE: ""

  db:
    image: mariadb:10.2
    #restart: always
    environment:
      MYSQL_DATABASE: 'ota'
      MYSQL_USER: 'ota'
      MYSQL_PASSWORD: 'ota'
      MYSQL_ROOT_PASSWORD: 'root'
    command:
      - docker-entrypoint.sh
      - --max-connections=10000
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db-bootstrap:/docker-entrypoint-initdb.d:ro
      - ota-db:/var/lib/mysql

  ota-lith:
    image: advancedtelematic/ota-lith:latest
    restart: always
    depends_on:
      - db
    command:
       - "/opt/ota-lith/bin/ota-lith"
       - "-Dconfig.file=/tmp/ota-lith.conf"
    labels:
      - traefik.enable=true
      - traefik.http.routers.reposerver.service=reposerver
      - traefik.http.routers.reposerver.rule=Host(`reposerver.ota.ce`)
      - traefik.http.services.reposerver.loadbalancer.server.port=7100
      - traefik.http.routers.keyserver.service=keyserver
      - traefik.http.routers.keyserver.rule=Host(`keyserver.ota.ce`)
      - traefik.http.services.keyserver.loadbalancer.server.port=7200
      - traefik.http.routers.director.service=director
      - traefik.http.routers.director.rule=Host(`director.ota.ce`)
      - traefik.http.services.director.loadbalancer.server.port=7300
      - traefik.http.routers.treehub.service=treehub
      - traefik.http.routers.treehub.rule=Host(`treehub.ota.ce`)
      - traefik.http.services.treehub.loadbalancer.server.port=7400
      - traefik.http.routers.deviceregistry.service=deviceregistry
      - traefik.http.routers.deviceregistry.rule=Host(`deviceregistry.ota.ce`)
      - traefik.http.services.deviceregistry.loadbalancer.server.port=7500
      - traefik.http.routers.campaigner.service=campaigner
      - traefik.http.routers.campaigner.rule=Host(`campaigner.ota.ce`)
      - traefik.http.services.campaigner.loadbalancer.server.port=7600
    volumes:
      - ./ota-lith-ce.conf:/tmp/ota-lith.conf
      - objects:/var/lib/ota-lith
     
  ota-lith-daemons:
    image: advancedtelematic/ota-lith:latest
    restart: always
    depends_on:
      - db
      - ota-lith
    command:
       - "/opt/ota-lith/bin/ota-lith"
       - "-main"
       - "com.advancedtelematic.ota_lith.OtaLithDaemonBoot"
       - "-Dconfig.file=/tmp/ota-lith.conf"
    volumes:
      - ./ota-lith-ce.conf:/tmp/ota-lith.conf

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.0.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  ota-db:
  objects:
