include required(file("src/main/resources/application.conf"))

ats {
  ota-lith = {
    db.default_host = "localhost"
    http.default_client_host = "localhost"
  }

  database {
    encryption {
      salt = "QyHon03eqkw="
      password = "kxHUuCWMLjUcEvsgaf3EfArToM79psmKsAJRMesApwEK9bdVdFNMpfcL7tKJkups"
    }
  }

  reposerver {
    storage {
      type = "local"
      localStorageRoot = "/tmp/ota-lith/tuf-objects"
    }
  }

  treehub {
    storage {
      type = "local"
      local {
        path = "/tmp/ota-lith/treehub-objects"
      }
    }
  }

  messaging {
    mode = "test"
  }
}
