
alter table `keys` MODIFY COLUMN `role_type` ENUM('ROOT', 'SNAPSHOT', 'TARGETS', 'TIMESTAMP', 'OFFLINE-UPDATES', 'OFFLINE-SNAPSHOT', 'REMOTE-SESSIONS') NOT NULL
;

alter table `key_gen_requests` MODIFY COLUMN `role_type` ENUM('ROOT', 'SNAPSHOT', 'TARGETS', 'TIMESTAMP', 'OFFLINE-UPDATES', 'OFFLINE-SNAPSHOT', 'REMOTE-SESSIONS') NOT NULL
;
