%% Ensure when adding entities here they match what's defined in the internal-docs repo
graph LR

subgraph Campaigner
  campaigner --> campaigner_maria_db
end
campaigner --> director
campaigner --> device_registry
