name: Release
on:
  push:
    tags: ["*"]

jobs:
  release-to-nexus:
    name: Release Jars
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_CLIENT_ID }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_SECRET }}
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      PGP_SECRET_KEY: ${{ secrets.PGP_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8
      - uses: coursier/cache-action@v6
      - run: echo $PGP_SECRET_KEY | base64 --decode | gpg --batch --import
      - run: sbt '+publishSigned ; sonatypeBundleRelease'

  build-images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8
      - uses: coursier/cache-action@v6
      - run: sbt docker:publishLocal
      - run: docker tag advancedtelematic/tuf-reposerver:$GITHUB_SHA uptane/tuf-reposerver:$GITHUB_SHA
      - run: docker tag advancedtelematic/tuf-keyserver:$GITHUB_SHA uptane/tuf-keyserver:$GITHUB_SHA
      - run: docker push uptane/tuf-reposerver:$GITHUB_SHA
      - run: docker push uptane/tuf-keyserver:$GITHUB_SHA

  release-garage-sign:
    name: Release garage-sign
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8
      - uses: coursier/cache-action@v6
      - run: sbt cli/packageZipTarball
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cli/target/universal/*.tgz
