version: '2'
services:
  toradex_ota_ui:
    container_name: toradex_ota_ui_cnt
    image: topeysoft/toradex-ota-frontend:latest
    # image: topeysoft/toradex-ota-frontend:1.1.103
    # build: .
    # restart: always
    ports:
      - 8085:4000
    # volumes:
    #   - ./docker-context/start.sh:/start.sh
    environment:
      - 'DISABLE_PROXY=1'
      - 'API_ENDPOINT_HOST=app-stable.int.toradex.com'
      - 'API_ENDPOINT_PORT=80'
      - 'SERVER_NAME=localhost'
      - 'SERVER_PORT=4000'
      - 'USER_POOL=dev'
      - 'DEMO_MODE=0'
