addSbtPlugin("com.typesafe.sbt"  % "sbt-git"       % "1.0.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "4.0.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.10.0")
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "3.1.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.4.0")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.8")
